import { useState } from 'react';
import { Check, UserRound, UsersRound, Plus, KeyRound, Copy, Share2, Settings, ArrowLeft, Trash2 } from 'lucide-react';
import type { Space, Member } from './spaces';
import type { Api } from './space-api';
import { SpaceDialog } from './space-dialog';
type Props={space:Space;spaces:Space[];userId:string;members:Member[];disabled:boolean;api:Api;onSelect:(id:string)=>void;onRefresh:()=>Promise<void>;onReload:()=>Promise<void>};
export function SpaceControls({space,spaces,userId,members,disabled,api,onSelect,onRefresh,onReload}:Props){
 const [view,setView]=useState<'menu'|'create'|'join'|'manage'|null>(null),[name,setName]=useState(''),[code,setCode]=useState(()=>sessionStorage.getItem('uchiwake-invite-code')||''),[preview,setPreview]=useState<{space_id:string;name:string;inviter:string}|null>(null);
 const [invite,setInvite]=useState<{code:string;expires_at:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const owner=space.owner_id===userId;
 const change=(next:typeof view)=>{setError('');setView(next);};
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const inviteText=invite?`「うちわけ」の「${space.name}」に招待します。\n招待コード：${invite.code}\nアプリを開き、右上のスペースアイコン →「招待コードで参加」で入力してください。\n48時間以内・1人用です。`:'';
 async function create(){await run(async()=>{const {space:created}=await api<{space:Space}>('/spaces',{method:'POST',body:JSON.stringify({name})});await onRefresh();onSelect(created.id);setView(null);});}
 async function join(){await run(async()=>{if(!preview){setPreview(await api('/spaces/invite-preview',{method:'POST',body:JSON.stringify({code})}));return;}const {space:joined}=await api<{space:Space}>('/spaces/join',{method:'POST',body:JSON.stringify({code,space_id:preview.space_id})});sessionStorage.removeItem('uchiwake-invite-code');await onRefresh();onSelect(joined.id);setView(null);});}
 return <><button type="button" className="space-switcher" disabled={disabled} aria-label={`スペースを切り替え：${space.name}`} title={space.name} aria-haspopup="dialog" aria-expanded={view!==null} onClick={()=>change('menu')}>{space.kind==='personal'?<UserRound size={23}/>:<UsersRound size={23}/>}</button>
 {view&&<SpaceDialog title={view==='menu'?'スペース':view==='create'?'スペースを作成':view==='join'?'招待コードで参加':space.name} menu={view==='menu'} busy={busy} onClose={()=>change(null)}>
 {view!=='menu'&&<button className="space-back" disabled={busy} onClick={()=>change('menu')}><ArrowLeft size={17}/>スペース一覧</button>}
 {error&&<p className="notice" role="alert">{error}</p>}
 {view==='menu'&&<div className="space-options">{spaces.map(s=><button key={s.id} aria-current={s.id===space.id?'true':undefined} onClick={()=>{onSelect(s.id);change(null);}}><span className="space-option-name">{s.name}<small>{s.kind==='personal'?'自分だけ':'共有'}</small></span>{s.id===space.id&&<Check size={17}/>} {s.kind==='personal'?<UserRound size={24}/>:<UsersRound size={24}/>}</button>)}<hr/><button onClick={()=>{setName('');change('create');}}><span>スペースを作成</span><Plus size={24}/></button><button onClick={()=>{setPreview(null);change('join');}}><span>招待コードで参加</span><KeyRound size={23}/></button>{space.kind==='shared'&&<button onClick={()=>{setName(space.name);change('manage');}}><span>このスペースの設定</span><Settings size={23}/></button>}</div>}
 {view==='create'&&<form onSubmit={e=>{e.preventDefault();void create();}}><label className="field"><span>スペース名</span><input autoFocus maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="ふたりの家計" disabled={busy}/></label><p className="subtle">作成後、招待コードでメンバーを追加できます。</p><button className="space-save" disabled={busy||!name.trim()}>{busy?'作成中…':'作成する'}</button></form>}
 {view==='join'&&<form onSubmit={e=>{e.preventDefault();void join();}}><label className="field"><span>招待コード</span><input autoFocus autoCapitalize="characters" autoComplete="off" spellCheck={false} value={code} disabled={busy} onChange={e=>{setCode(e.target.value);setPreview(null);sessionStorage.setItem('uchiwake-invite-code',e.target.value);}} placeholder="XXXX-XXXX-XXXX"/></label>{preview&&<div className="space-join-preview"><strong>{preview.name}</strong><p>{preview.inviter}さんからの招待</p><p className="subtle">このスペースの家計を一緒に閲覧・編集できます。</p></div>}<button className="space-save" disabled={busy||!code.trim()}>{busy?'確認中…':preview?'このスペースに参加':'参加先を確認'}</button></form>}
 {view==='manage'&&<div className="space-manage">{owner&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`/spaces/${space.id}/name`,{method:'PUT',body:JSON.stringify({name})});await onRefresh();});}}><label className="field"><span>スペース名</span><input value={name} maxLength={40} disabled={busy} onChange={e=>setName(e.target.value)}/></label><button className="space-save" disabled={busy||!name.trim()||name.trim()===space.name}>名前を保存</button></form>}
 <h3>メンバー</h3>{members.filter(m=>m.active).map(m=><div className="space-member" key={m.user_id}><UserRound size={19}/><span>{m.name}{m.user_id===userId?'（あなた）':''}<small>{m.user_id===space.owner_id?'作成者':'メンバー'}</small></span>{owner&&m.user_id!==userId&&<button aria-label={`${m.name}をメンバーから外す`} disabled={busy} onClick={()=>{if(confirm(`${m.name}さんを外しますか？ 過去の負担額は保持されます。未使用の招待コードは無効になります。`))void run(async()=>{await api(`/spaces/${space.id}/members/${encodeURIComponent(m.user_id)}`,{method:'DELETE'});await onReload();});}}><Trash2 size={18}/></button>}</div>)}
 {owner&&<><button className="space-save" disabled={busy} onClick={()=>void run(async()=>{setInvite(await api(`/spaces/${space.id}/invites`,{method:'POST',body:'{}'}));setCopied(false);})}>{invite?'別の招待コードを作る':'メンバーを招待'}</button>{invite&&<div className="space-invite"><strong>{invite.code}</strong><small>1人用 · {new Date(invite.expires_at).toLocaleString('ja-JP')}まで</small><div><button disabled={busy} onClick={()=>void run(async()=>{await navigator.clipboard.writeText(inviteText);setCopied(true);})}><Copy size={17}/>{copied?'コピーしました':'招待文をコピー'}</button>{!!navigator.share&&<button onClick={()=>void navigator.share({text:inviteText}).catch(e=>{if(e.name!=='AbortError')setError('共有できませんでした。招待文をコピーしてください');})}><Share2 size={17}/>共有</button>}</div></div>}<button className="space-delete" disabled={busy} onClick={()=>{if(confirm(`「${space.name}」を削除しますか？ メンバー全員がアクセスできなくなります。`))void run(async()=>{await api(`/spaces/${space.id}/space`,{method:'DELETE'});await onRefresh();onSelect(spaces.find(s=>s.kind==='personal')!.id);});}}><Trash2 size={17}/>スペースを削除</button></>}
 </div>}
 </SpaceDialog>}</>;
}
